# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl"]

# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "docker_data"]

# Watch these directories if you specified.
include_dir = []

# Exclude files.
exclude_file = []

# Exclude unchanged files.
exclude_unchanged = true

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 300 # ms
# Stop running old binary when build errors occur.
stop_on_error = true



[misc]
# Delete tmp directory on exit
clean_on_exit = true
